# declares package dependencies, assets, fonts, environment SDK constraints, and dev tools.

name: SwishLab
description: Manual migration from FlutterFlow
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0

  # text
  font_awesome_flutter: ^10.12.0
  google_fonts: ^7.0.0
  flutter_md: ^0.0.8

  # widget helpers
  smooth_page_indicator: ^2.0.0
  easy_debounce: ^2.0.0

  # media
  video_player: ^2.8.2
  image_picker: ^1.0.7
  lottie: ^3.3.2

  # file paths
  path_provider: ^2.1.5
  path: ^1.9.1

  # state management & routing
  flutter_riverpod: ^3.1.0
  go_router: ^17.0.0

  # networking / auth / storage
  dio: ^5.0.0
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  http: ^1.6.0

  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  widgetbook: ^3.20.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/lottie/
    - assets/json/
    - assets/fonts/
    - assets/icons/
    - assets/gifs/
    - assets/markdown/
